# LLMProxy 测试配置文件
# 基于火山引擎 API 的简化测试配置
# 用于测试 llmproxyd 的基本功能

#-------------------------------------------------------------------------------
# HTTP 服务器配置 (httpServer)
#-------------------------------------------------------------------------------
httpServer:
  #-----------------------------------------------------------------------------
  # 转发服务 (forwards)
  #-----------------------------------------------------------------------------
  forwards:
    # 火山引擎 API 转发服务
    - name: volcengine_proxy
      port: 3000
      address: "0.0.0.0"
      defaultGroup: "volcengine_group"
      # 速率限制测试
      ratelimit:
        perSecond: 50
        burst: 100
      # 连接超时测试
      timeout:
        idle: 120000
        read: 60000
        write: 60000

  #-----------------------------------------------------------------------------
  # 管理服务 (admin)
  #-----------------------------------------------------------------------------
  admin:
    port: 9003
    address: "0.0.0.0"
    timeout:
      idle: 60000
      read: 30000
      write: 30000

#-------------------------------------------------------------------------------
# 上游服务定义 (upstreams)
#-------------------------------------------------------------------------------
upstreams:
  # 火山引擎 API 端点
  - name: volcengine_primary
    url: "https://ark.cn-beijing.volces.com"
    auth:
      type: "bearer"
      token: "0b252972-c113-452b-801e-6e283dd13eba"
    headers:
      - op: "insert"
        key: "Content-Type"
        value: "application/json"
      - op: "insert"
        key: "X-LLMProxy-Test"
        value: "VolcEngine-Test"
    # 熔断器测试
    breaker:
      threshold: 0.6
      cooldown: 30000
    # 限速器测试
    ratelimit:
      perSecond: 20

#-------------------------------------------------------------------------------
# 上游组定义 (upstreamGroups)
#-------------------------------------------------------------------------------
upstreamGroups:
  # 火山引擎上游组
  - name: volcengine_group
    upstreams:
      - name: volcengine_primary
    balance:
      strategy: "roundrobin"
    httpClient:
      agent: "LLMProxy/1.0 (VolcEngineTest)"
      keepalive: 90
      connect:
        idleTotal: 50
        idlePerHost: 5
        maxPerHost: 20
      timeout:
        connect: 15
        request: 300
        idle: 90
      retry:
        attempts: 2
        initial: 1000
